import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const navigationLinks = [
  { href: "/", label: "Home" },
  { href: "/werewolf-general", label: "Werewolf" },
  { href: "/tier-list", label: "Tier List" },
  { href: "/faq", label: "FAQ" },
  { href: "/research", label: "Research" },
  { href: "/jazzarus", label: "Jazzarus" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${styles.body} min-h-full flex flex-col`}>
        <header>
          <div className={styles.banner}>BANNER</div>

          <nav className={styles.navbar} aria-label="Main navigation">
            <ul className={styles.navList}>
              {navigationLinks.map((link) => (
                <li key={link.label}>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>

        <div className={styles.pageLayout}>
          <div className={styles.content}>{children}</div>

          <aside className={styles.sidebar}>
            <section>
              <h2>YouTube</h2>
              <div className={styles.mediaPlaceholder}>
                YouTube placeholder
              </div>
            </section>

            <section>
              <h2>Twitch</h2>
              <div className={styles.mediaPlaceholder}>
                Twitch placeholder
              </div>
            </section>
          </aside>
        </div>
      </body>
    </html>
  );
}
